name:                aoc2016
version:             0.1.0.0
github:              "mstksg/advent-of-code-2016"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            "Development environment for Advent of Code challenges"
category:            Web

description: |
  Scaffolding for an integrated development environment for Advent of Code
  challenges.  Includes auto-runner, prompt displays and countdowns, and
  integrated submissions.

ghc-options:
- -Wall
- -Wcompat
- -Wno-partial-type-signatures
- -Wredundant-constraints

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- BlockArguments
- DataKinds
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImplicitParams
- KindSignatures
- LambdaCase
- MonadComprehensions
- MonoLocalBinds
- MultiParamTypeClasses
- MultiWayIf
- NumDecimals
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeInType
- TypeOperators
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src
  dependencies:
  - advent-of-code-api >= 0.2.2.1
  - cryptonite
  - aeson
  - memory
  - ansi-terminal
  - bytestring
  - base16
  - containers
  - criterion
  - finitary
  - data-default-class
  - data-memocombinators
  - deepseq
  - directory
  - filepath
  - finite-typelits
  - foldl
  - groups
  - hashable
  - haskeline
  - haskell-names
  - haskell-src-exts
  - hpack
  - lens
  - linear
  - megaparsec
  - mtl
  - nonempty-containers
  - pandoc
  - parallel
  - parser-combinators
  - profunctors
  - psqueues
  - semigroupoids
  - split
  - template-haskell
  - text
  - time
  - transformers
  - vector-sized
  - yaml

executables:
  aoc2016:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ansi-terminal
    - aoc2016
    - containers
    - deepseq
    - finite-typelits
    - lens
    - optparse-applicative

tests:
  aoc2016-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2016
    - ansi-terminal

benchmarks:
  aoc2016-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aoc2016
